### ISSUE TITLE
Getting Oops Page from Auth0

### ISSUE THREAD

**Issue by daltonch** [experoinc/aws-lambda-edge-oauth#3]
Thanks for building this! I have setup the configuration bucket as described and have the config file in there I have setup my tenant name as instructed, however when visiting the distribution I get redirected to the Oops page from Auth0, specifically its this URL,

https://<TENANT>.auth0.com/u/login

the previous call is to the login page,
https://<TENANT>.auth0.com/login?client=<CLIENT_ID>&redirect_uri=https%3A%2F%2F<MYSITE>%2Flogincb%3Fdest%3D%252F

I do not have a route called /logincb I assume this is something your lambda? Or does this need to be a defined route? Any other ideas on what I can check or debug to get past the Oops? I never get a login prompt or anything, just a call to 
<MYSITE>/  (302)
https://<TENANT>.auth0.com/login?client=.... (302)
https://<TENANT>.auth0.com/u/login. (400) and oops

Thanks!

**Comment by bman654** [comment]
yes the logincb endpoint is handled by the lambda.  Sometimes the Ooops page has a small link beneath the message that will provide more detail to the config issue.

- Check that in auth0 app you have added the https://websitedomain/logincb to the allowed callback 
- check auth0 app, Advanced > OAuth that OIDC Conformant switch is OFF (the lambda is not oidc comformant right now)

if those turn up nothing, then maybe post complete urls (with domain name and clientid redacted) along with screenshot of auth0 app setup (also with private info redacted) and I can tell you what's missing.

**Comment by daltonch** [comment]
Yes I have the CB allowed and turned off OIDC, i just checked auth0 logs and saw this,

> A user has attempted to access a login page directly. This is not supported unless a "Application Login URI" is set for your application, or a "Tenant Login URI" is set for your tenant. For more information, see: https://auth0.com/docs/universal-login/default-login-url

I'll grab the other stuff you asked for just through I'd post this incase it means anything to you. Appreciate the help.

**Comment by bman654** [comment]
is your auth0 application type "Regular Web Application"?  I don't have either of those URIs defined in any of the apps or tenants where we use this lambda (which admittedly should be updated to use the authorize endpoint)

**Comment by daltonch** [comment]
URL's from DevTools/Network

https://`<myhost>`/
https://`<TENANT>`.auth0.com/login?client=`<clientid>`&redirect_uri=https%3A%2F%2F`<myhost>`%2Flogincb%3Fdest%3D%252F

redated portion is `<myhost>`

![Screen Shot 2022-08-17 at 11 11 09 AM](https://user-images.githubusercontent.com/7874711/185189924-10c4d049-8c56-4fc0-8d4f-5a1d4558db11.png)

If you need more from the Auth0 page just let me know. Thanks!

**Comment by daltonch** [comment]
Just saw your other commend, no it's defined as a Single Page App as we were originally trying to do the Auth with vue but then siwtched to static files, should I change it to regular?

**Comment by bman654** [comment]
Yes the lambda acts like a traditional web application to Auth0, not an SPA

--
Brandon

**Comment by daltonch** [comment]
So I created a new Regular Web Application, changed the Client ID, Client Secret in the Config and added the callback and turned off OIDC in the application, no other changes. I still get the same Oops message. Is there somewhere I can just send you the domain and you can look at it? I'm not sure where it's getting https://tenant.auth0.com/u/login. (the /u/ piece is confusing to me).

Appreciate the assistance.

**Comment by bman654** [comment]
You can email the url to Brandon at experoinc com and I’ll compare the network calls I get against the sites I have and see if anything looks different 

--
Brandon

**Comment by bman654** [comment]
I googled for `auth0 /u/login` and landed on this page: https://auth0.com/docs/authenticate/login/auth0-universal-login

I'm guessing you have the new experience turned on.  I've only ever tested with it turned off.

Here are two options you can try:

- Switch to classic login and see if that fixes the problem

or...

- try this to use the /authorize endpoint instead (which is what this lambda should be doing anyway...)

1. change the `AUTH0_LOGIN_URL` to be `https://YOURDOMAIN.auth0.com/authorize` in the lambda config file
2. edit [line 132](https://github.com/experoinc/aws-lambda-edge-oauth/blob/master/index.js#L132) to look like this:

```javascript
const redirectUrl = `${config.AUTH0_LOGIN_URL}?client_id=${config.AUTH0_CLIENT_ID}&redirect_uri=${encodedCallback}&response_type=code&state=${Date.now()}`;
```

That should add the necessary parameters to make the lambda work with the /authorize endpoint.

If the 2nd method solves your issue I'll update the lambda.

**Comment by daltonch** [comment]
Yes, we do have new experience turned on. I used another tenant where we do not have new experience on and it worked!

Thanks for the pointer. I didn't try the second suggestion yet. 

Appreciate the help!

**Comment by wojciech-niedzwiedz-napa** [comment]
Hi @bman654 
Really appreciate this project!
I had the same issue as here but I opted to follow solution nr 2 and I changed my config and redirect line.
Auth0 login page properly shows, only after logging in I'm redirected to this url
https://<DOMAIN>/callback?dest=%2F&code=<CODE>&state=<STATE>
and it redirects me to my json object containing jwt token.
Can I create an issue for this?
