### ISSUE TITLE
Redirected to JSON with 401 instead of index.html

### ISSUE THREAD

**Issue by wojciech-niedzwiedz-napa** [experoinc/aws-lambda-edge-oauth#4]
Hi
Really appreciate this project!
I had the same issue as here:
https://github.com/experoinc/aws-lambda-edge-oauth/issues/3

but I opted to follow solution nr 2 and I changed my config and redirect line.
Auth0 login page properly shows, only after logging in I'm redirected to this url
https://domain/callback?dest=%2F&code=CODE&state=STATE
Cookies are saved after login, but it redirects me to my json object containing jwt token, network tab shows 401 for the above URL.
I tried setting Token Endpoint Authentication Method in Auth0 to both None or POST, but the effect is the same.

**Comment by wojciech-niedzwiedz-napa** [comment]
session-token is empty so I think I exit through here in the lambda:
callback(null, redirect(redirectUrl, [{name: "session-token", value: ""}]));

**Comment by wojciech-niedzwiedz-napa** [comment]
I think I know what was the issue:
line
const token = json.id_token;
should be
const token = json.access_token;

It still doesn't work though, now it causes too many redirects followed by Bad Token Response: 403 undefined

**Comment by wojciech-niedzwiedz-napa** [comment]
The err from validateToken(...) says
JsonWebTokenError: jwt malformed

**Comment by bman654** [comment]
The response might be slightly different.  Since `json.id_token` is not working, you could try logging the entire response json (`console.log(JSON.stringify(json))`) to see what is received when we exchange the code for token.

**Comment by wojciech-niedzwiedz-napa** [comment]
I tried using jwt, but it just says that the token is malformed.
I'm trying this approach as it seems relevant:
https://community.auth0.com/t/access-token-is-malformed-jwt-when-authenticating-with-google-oauth2/74218/6

**Comment by wojciech-niedzwiedz-napa** [comment]
That was it, I have the necessary changes to make universal login work then, if you want me to create a PR on Monday :)
Cheers!

**Comment by bman654** [comment]
oh that would be great if you did.  It might even solve the "OIDC Compliant" issue.

**Comment by wojciech-niedzwiedz-napa** [comment]
I have a PR ready, do you want to give me the ability to push to remote non-master branch or should I fork?

**Comment by bman654** [comment]
I think easiest is fork.

**Comment by wojciech-niedzwiedz-napa** [comment]
Here you go
I'm closing this issue
https://github.com/experoinc/aws-lambda-edge-oauth/pull/5
